# Generated by Django 5.2 on 2025-05-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
    ]
