# Generated by Django 5.2 on 2025-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0002_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('ST', 'Starter'), ('MC', 'Main Course'), ('DE', 'Dessert'), ('DR', 'Drinks'), ('SN', 'Snacks')], default='MC', max_length=50),
        ),
    ]
