# Generated by Django 5.2 on 2025-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0005_review_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
