# Generated by Django 5.2 on 2025-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0006_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
