# Generated by Django 5.2 on 2025-06-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0010_alter_order_options_remove_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
