# Generated by Django 5.2 on 2025-06-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0013_remove_order_delivery_date_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='savorybites.order'),
        ),
    ]
