# Generated by Django 5.2 on 2025-06-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0014_remove_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_payment_method',
        ),
    ]
