# Generated by Django 5.2 on 2025-06-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0016_order_order_id_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
