# Generated by Django 5.2 on 2025-06-14 05:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savorybites', '0017_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
